### ISSUE TITLE
couldnt find interface: VDebugOverlay003

### ISSUE THREAD

**Issue by Snowywasbanned** [caxanga334/NavBot#1]
L 10/10/2024 - 21:02:42: [SM] Unable to load extension "navbot.ext": Could not find interface: VDebugOverlay003

**Comment by caxanga334** [comment]
Need more information.

- Operating system.
- Game/mod

**Comment by Snowywasbanned** [comment]
it's linux and team fortress 2, trying to run the extension on mvm. bwrr

> Need more information.
> 
> * Operating system.
> * Game/mod

it's linux and team fortress 2, trying to run the extension on mvm. bwrr
